### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by SolidOceanTrust** [CiscoDevNet/intersight-powershell#11]
Hello,
I am trying to load the module for the first time and found the "Getting Started" process very difficult.
In each of the cmdlet documentation section, there is a small section for building a `$configuration` variable, but the cmdlet that is responsible for generating that object is incorrect.

[Source](https://github.com/CiscoDevNet/intersight-powershell/blob/master/docs/IntersightAdapterApi.md#Get-IntersightAdapterHostEthInterfaceByMoid)

```
# general setting of the PowerShell module, e.g. base URL, authentication, etc
$Configuration = Get-Configuration
# Configure API key authorization: cookieAuth
$Configuration.ApiKey.X-Starship-Token = "YOUR_API_KEY"
```
I had to dig into the code to see that it should be
$Configuration = Get-**Intersight**Configuration

If you could make a "Getting Started" section about how to setup and configure the client, I think that would really really help other users adopt the module.
Thanks!
SOT

**Comment by Ghufz** [comment]
updated the gettingStarted.md :- https://github.com/CiscoDevNet/intersight-powershell/pull/13

Note :- the Intersight module has been changed and it contains the breaking changes.

follow the instruction form gettingStarted.md and install the latest module from [PSGallery](https://www.powershellgallery.com/packages/Intersight.PowerShell)
