### ISSUE TITLE
How add vlans with Api powershell script

### ISSUE THREAD

**Issue by grassman80bz** [CiscoDevNet/intersight-powershell#110]
Good morning,
I am trying to simplify my life in configuring all the necessary vlans for the migration from the old UCS to the new intersight.
At the moment I have managed to get the policy level vlans created for the fabric in this way, at the moment I am passing the vlan in static mode but I am just testing:

This part works as desired:
```
$v_is_cfgFabEthnPol = Get-IntersightFabricEthNetworkPolicy -name "UCSX-VLAN-POLICY" | Get-IntersightMoMoRef
$v_is_cfgFabMulcPol = Get-IntersightFabricMulticastPolicy -name "UCSX-MULTICAST-POLICY" | Get-IntersightMoMoRef
New-IntersightFabricVlan -Name vlan_1111 -VlanId 1111 -EthNetworkPolicy $v_is_cfgFabEthnPol -MulticastPolicy $v_is_cfgFabMulcPol -SharingType None -AutoAllowOnUplinks $true
```

What I then fail to do is to define the same vlan in the NetworkGroupPolicy, called in my case UCSX-VLAN-VM-POLICY.

I was thinking of something like this, but here too there is a lack of examples and I cannot understand the correct syntax.
So I'm stuck.

This part does **not** work as desired:

```
$VlanToAdd=Get-IntersightFabricVlan -VlanId 1111
$VlanToVM=(Get-IntersightFabricEthNetworkGroupPolicy -name UCSX-VLAN-VM-POLICY).VlanSettings.AllowedVlans
new-intersightFabricEthNetworkGroupPolicy -Name UCSX-VLAN-VM-POLICY -VlanSettings -AdditionalProperties @{ AllowedVlans = $VlanToAdd}

```
As I have to define more than 1000 vlans, between the various environments, I need your help and thank you very much.

Daniel

**Comment by briamorr** [comment]
If you are trying to create a new policy all together this should work:

```
$org=Get-IntersightOrganizationOrganization -Name 'default'
$vlans = Initialize-IntersightFabricVlanSettings -AllowedVlans "1,2,3,4,1111" -NativeVlan 1111
New-IntersightFabricEthNetworkGroupPolicy -Name briamorr-networkgroup -VlanSettings $vlans -Organization $org
```

If you are trying to add vlans to an existing policy you'll have to read in and manipulate the existing object's vlan list otherwise it'll just overwrite

```
$org=Get-IntersightOrganizationOrganization -Name 'default'
$existingPolicy = Get-IntersightFabricEthNetworkGroupPolicy -Name briamorr-networkgroup
$allowedVlans = $existingPolicy.VlanSettings.AllowedVlans
$allowedVlans += ",888"
$vlans = Initialize-IntersightFabricVlanSettings -AllowedVlans $allowedVlans -NativeVlan $existingPolicy.VlanSettings.NativeVlan
$existingPolicy | Set-IntersightFabricEthNetworkGroupPolicy -VlanSettings $Vlans
```

There is also the IMM transition tool if its a one time event where you can copy existing config objects from UCSM into their respective Intersight format

**Comment by briamorr** [comment]
If the profile/policy is attached to equipment each change request will trigger profile validation.  You might be able to do a single request with New-IntersightBulkRequest so the profile only goes through a single validation and not 1000 times but its not as nice looking as the regular cmdlets (unless anyone else has different ideas)

```
$org = Get-IntersightOrganizationOrganization -Name "default"
$fabricEthNetworkPolicy = Get-IntersightFabricEthNetworkPolicy -Name "briamorr-vlan" -Organization $org
$fabricMulticastPolicy = Get-IntersightFabricMulticastPolicy -Name "briamorr-multicast" -Organization $org

$VlanForFabric=5,11,18,40,47,49,54,58,61,202,204,224,238,777,778,901,905,1010,1011,1012,1013,1014,1031,1065,1067,1249,1299,1300,1304,1630

$request = New-Object -TypeName "System.Collections.ArrayList"
$request = [System.Collections.ArrayList]@()

$additionalProps = ""

foreach($vlan in $VlanForFabric){
	$additionalProps = '{"AutoAllowOnUplinks": true,"EthNetworkPolicy": "'+$fabricEthNetworkPolicy.Moid+'","IsNative": false,"MulticastPolicy": "'+$fabricMulticastPolicy.Moid+'","Name": "vlanprefix_'+$vlan+'","PrimaryVlanId": 0,"SharingType": "None","VlanId": '+$vlan+'}'
    $additionalProps = ConvertFrom-Json -InputObject $additionalProps -AsHashtable
    $additionalPropsObj = New-Object System.Collections.Generic.Dictionary"[String,Object]"
    $additionalPropsObj.Add("Body",$additionalProps)
    $request += Initialize-IntersightBulkSubRequest -Verb "POST" -Uri "/v1/fabric/Vlans" -AdditionalProperties $additionalPropsObj
}

New-IntersightBulkRequest -Requests $request

```

**Comment by briamorr** [comment]
Was thinking this seems a bit better if you don't want to worry about JSON

```
$org = Get-IntersightOrganizationOrganization -Name "default"
$fabricEthNetworkPolicy = Get-IntersightFabricEthNetworkPolicy -Name "briamorr-vlan" -Organization $org | Get-IntersightMoMoRef
$fabricMulticastPolicy = Get-IntersightFabricMulticastPolicy -Name "briamorr-multicast" -Organization $org  | Get-IntersightMoMoRef

$request = New-Object -TypeName "System.Collections.ArrayList"
$request = [System.Collections.ArrayList]@()

$VlanForFabric=5,11,18,40,47,49,54,58,61,202,204,224,238,777,778,901,905,1010,1011,1012,1013,1014,1031,1065,1067,1249,1299,1300,1304,1630

foreach($vlan in $VlanForFabric){
    $additionalProps = Initialize-IntersightFabricVlan -Name ("vlan_"+$vlan) -VlanId $vlan -EthNetworkPolicy $fabricEthNetworkPolicy -MulticastPolicy $fabricMulticastPolicy -SharingType None -AutoAllowOnUplinks $true
    $additionalPropsObj = New-Object System.Collections.Generic.Dictionary"[String,Object]"
    $additionalPropsObj.Add("Body",$additionalProps)
    $request += Initialize-IntersightBulkSubRequest -Verb "POST" -Uri "/v1/fabric/Vlans" -AdditionalProperties $additionalPropsObj
}

New-IntersightBulkRequest -Requests $request
```

**Comment by grassman80bz** [comment]
hi briamorr,

why can't find the cmdlet?

Initialize-IntersightFabricVlan: 
Line |
   2 |      $additionalProps = Initialize-IntersightFabricVlan -Name ("vlan_" …
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Initialize-IntersightFabricVlan' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Initialize-IntersightBulkSubRequest: 

I have use this import:
Import-Module -Name '.\Intersight.PowerShell'

All the other command are present, not the on that starts with Inizialize-IntersightF* (see picture for a better explanation)
Can you help me please?


![NoCmdlet](https://github.com/CiscoDevNet/intersight-powershell/assets/93379527/1b740bb2-d47e-4e16-97dc-1b47efc72ddd)

**Comment by grassman80bz** [comment]
Hi briamorr,
thanks for your help.
I have import the module like this:

`Import-Module -Name 'Intersight.PowerShell'`

but the cmdlet _Initialize-IntersightFabricVlan_ and _Initialize-IntersightBulkSubRequest_ are not present for me.. how can i resolve?

see picture for bettere understanding.
![NoCmdlet](https://github.com/CiscoDevNet/intersight-powershell/assets/93379527/1b71352e-b672-4e56-8d10-1c5a193c7a00)

thanks

**Comment by grassman80bz** [comment]
PS C:\git\ristoolw\User_Experience_Monitor> get-module -name Intersight.Powershell   

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.11.13…            Intersight.PowerShell               {Get-IntersightAaaAuditRecord, Get-IntersightAaaRetentionConfig, Get-IntersightAaaRetentionPolicy, New-IntersightAaaRetentionPolicy…}

$x=get-module -name Intersight.Powershell

PS C:\git\ristoolw\User_Experience_Monitor> $x.ExportedCommands.Keys | Where-Object {$_ -like "Initialize*"}
Initialize-IntersightAaaAuditRecord
Initialize-IntersightAaaRetentionConfig
Initialize-IntersightAaaRetentionPolicy
Initialize-IntersightAccessAddressType
Initialize-IntersightAccessConfigurationType
Initialize-IntersightAccessIpAddress
Initialize-IntersightAccessPolicy
Initialize-IntersightAccessPolicyInventory
Initialize-IntersightAdapterAdapterConfig
Initialize-IntersightAdapterConfigPolicy
Initialize-IntersightAdapterDceInterfaceSettings
Initialize-IntersightAdapterEthSettings
Initialize-IntersightAdapterExtEthInterface
Initialize-IntersightAdapterFcSettings
Initialize-IntersightAdapterHostEthInterface
Initialize-IntersightAdapterHostFcInterface
Initialize-IntersightAdapterHostIscsiInterface
Initialize-IntersightAdapterPortChannelSettings
Initialize-IntersightAdapterUnit
Initialize-IntersightAdapterUnitExpander
Initialize-IntersightApplianceApiStatus
Initialize-IntersightApplianceAppOpStatus
Initialize-IntersightApplianceAppStatus
Initialize-IntersightApplianceAutoRmaPolicy
Initialize-IntersightApplianceBackup
Initialize-IntersightApplianceBackupPolicy
Initialize-IntersightApplianceCertRenewalPhase
Initialize-IntersightApplianceCertificateSetting
Initialize-IntersightApplianceClusterInfo
Initialize-IntersightApplianceClusterInstall
Initialize-IntersightApplianceClusterInstallPhase
Initialize-IntersightApplianceClusterReplaceNode
Initialize-IntersightApplianceDataExportPolicy
Initialize-IntersightApplianceDeviceCertificate
Initialize-IntersightApplianceDeviceClaim
Initialize-IntersightApplianceDeviceClusterInstall
Initialize-IntersightApplianceDeviceUpgradePolicy
Initialize-IntersightApplianceDiagSetting
Initialize-IntersightApplianceExternalSyslogSetting
Initialize-IntersightApplianceFileGateway
Initialize-IntersightApplianceFileSystemOpStatus
Initialize-IntersightApplianceFileSystemStatus
Initialize-IntersightApplianceGroupOpStatus
Initialize-IntersightApplianceGroupStatus
Initialize-IntersightApplianceImageBundle
Initialize-IntersightApplianceKeyValuePair
Initialize-IntersightApplianceMetaManifest
Initialize-IntersightApplianceNetworkLinkStatus
Initialize-IntersightApplianceNetworkStatus
Initialize-IntersightApplianceNodeInfo
Initialize-IntersightApplianceNodeIpInfo
Initialize-IntersightApplianceNodeOpStatus
Initialize-IntersightApplianceNodeStatus
Initialize-IntersightApplianceReleaseNote
Initialize-IntersightApplianceRemoteFileImport
Initialize-IntersightApplianceRestore
Initialize-IntersightApplianceSetupInfo
Initialize-IntersightApplianceStatusCheck
Initialize-IntersightApplianceSystemInfo
Initialize-IntersightApplianceSystemOpStatus
Initialize-IntersightApplianceSystemStatus
Initialize-IntersightApplianceUpgrade
Initialize-IntersightApplianceUpgradePolicy
Initialize-IntersightAssetAddressInformation
Initialize-IntersightAssetAlarmSummary
Initialize-IntersightAssetApiKeyCredential
Initialize-IntersightAssetClaimSignature
Initialize-IntersightAssetClientCertificateCredential
Initialize-IntersightAssetCloudConnection
Initialize-IntersightAssetClusterMember
Initialize-IntersightAssetConnection
Initialize-IntersightAssetContractInformation
Initialize-IntersightAssetCredential
Initialize-IntersightAssetCustomerInformation
Initialize-IntersightAssetDeployment
Initialize-IntersightAssetDeploymentAlarmInfo
Initialize-IntersightAssetDeploymentDevice
Initialize-IntersightAssetDeploymentDeviceAlarmInfo
Initialize-IntersightAssetDeploymentDeviceInformation
Initialize-IntersightAssetDeviceClaim
Initialize-IntersightAssetDeviceConfiguration
Initialize-IntersightAssetDeviceConnectorManager
Initialize-IntersightAssetDeviceContractInformation
Initialize-IntersightAssetDeviceContractNotification
Initialize-IntersightAssetDeviceEndpointLocalCredential
Initialize-IntersightAssetDeviceInformation
Initialize-IntersightAssetDeviceRegistration
Initialize-IntersightAssetDeviceStatistics
Initialize-IntersightAssetDeviceTransaction
Initialize-IntersightAssetGenericTargetClaimOptions
Initialize-IntersightAssetGlobalUltimate
Initialize-IntersightAssetGoogleCloudPlatformServiceAccountKeyCredential
Initialize-IntersightAssetHttpConnection
Initialize-IntersightAssetIntersightDeviceConnectorConnection
Initialize-IntersightAssetMeteringType
Initialize-IntersightAssetNewRelicCredential
Initialize-IntersightAssetNoAuthenticationCredential
Initialize-IntersightAssetOauthBearerTokenCredential
Initialize-IntersightAssetOauthClientIdSecretCredential
Initialize-IntersightAssetOrchestrationHitachiVirtualStoragePlatformOptions
Initialize-IntersightAssetOrchestrationHsmVmwareVcenterOptions
Initialize-IntersightAssetOrchestrationService

**Comment by briamorr** [comment]
What happens if you try to run those cmdlets in the shell?  I spun up a new virtual machine and they seem to be working on there as well.  

```
PS C:\Intersight> get-command -Module Intersight.Powershell | Where-Object -Property Name -EQ 'Initialize-IntersightFabricVlan'  | ft -Autosize

CommandType Name                            Version      Source
----------- ----                            -------      ------
Cmdlet      Initialize-IntersightFabricVlan 1.0.11.13236 Intersight.PowerShell

PS C:\Intersight> get-command -Module Intersight.Powershell | Where-Object -Property Name -EQ 'Initialize-IntersightBulkSubRequest' | ft -Autosize

CommandType Name                                Version      Source
----------- ----                                -------      ------
Cmdlet      Initialize-IntersightBulkSubRequest 1.0.11.13236 Intersight.PowerShell

**Comment by grassman80bz** [comment]
Hi,
i have installed the last version of the module and now i see all the cmdlet.
I will try to create a script with your suggestion.

Thanks for your help.

**Comment by Ghufz** [comment]
You may use below script also.

```powershell
#Get the organization MO.
$org = Get-IntersightOrganizationOrganization -Name "PSOrg"
# Get the EthNetworkPolicy Either based on Moid or Name and Organization
$EthNetworkPolicy = Get-IntersightFabricEthNetworkPolicy -Name "ethNetworkPolicy" -Organization $org
$EthNetworkPolicyRef = $EthNetworkPolicy | Get-IntersightMoMoRef

# Get the EthNetworkPolicy Either based on Moid or Name and Organization
$MulticastPolicy = Get-IntersightFabricMulticastPolicy -Name "multiCastPolicy" -Organization $org
$MulticastPolicyRef = $MulticastPolicy | Get-IntersightMoMoRef

#Add new Vlans to existing EthNetworkPolicy
$newVlanIds = @(11,12,13,15)

foreach($item in $newVlanIds){
    $result = New-IntersightFabricVlan -Name $($NewPrefix+$item) -VlanId $item -EthNetworkPolicy $EthNetworkPolicyRef -MulticastPolicy $MulticastPolicyRef
    $UpdatedVlans +=$result
}


```
