### ISSUE TITLE
API object type for Chassis Slots?

### ISSUE THREAD

**Issue by wgjhstt247** [CiscoDevNet/intersight-powershell#115]
In UCS Manager XML API, there was a powertools command to get chassis slot objects and their status:
Get-UcsFabricComputeSlotEp

This function was helpful to see which slots were unpopulated in a UCS Domain at a high level. I'm unable to find a function like this in the Intersight API. Do you know what object type this would be in the Intersight API, or do I need to infer which slots are unpopulated based on slotted blade servers, decommissioned blade servers, and chassis model?

**Comment by vvb** [comment]
You could do the following. It fetches all the servers that are a part of a given chassis and lists the ChassisId and SlotId.

```
$chassis_moid = $(Get-IntersightEquipmentChassis -Name chassis-2).Moid
$filter = "Ancestors.Moid eq '$chassis_moid'"
$servers = Get-IntersightComputePhysicalSummary -Filter $filter
$servers.Results | Format-Table Name,ChassisId,SlotId
```
