### ISSUE TITLE
Detach Server Profile from Template using PowerShell

### ISSUE THREAD

**Issue by ivacuna** [CiscoDevNet/intersight-powershell#116]
Hello,

I'm having difficulty identifying the syntax/cmdlet(s) to detach a server profile from template using Intersight.PowerShell (v1.0.11.9661). 

![image](https://github.com/CiscoDevNet/intersight-powershell/assets/134341388/33d74cf5-73db-460d-a395-4e9daf3ad9bf)

Can you help point us in the right direction?

Thank you,
Ivan

**Comment by vvb** [comment]
This should work - `$profileMo | Set-IntersightServerProfile -SrcTemplate $null`

**Comment by ivacuna** [comment]
That was it, thank you, much appreciated!
