### ISSUE TITLE
Activate Server Profile with Set-IntersightServerProfile

### ISSUE THREAD

**Issue by ivacuna** [CiscoDevNet/intersight-powershell#119]
Below commands will assign a blade server to a server profile and deploy the server profile:

```
Get-IntersightServerProfile $server | Set-IntersightServerProfile -AssignedServer (Get-IntersightComputeBlade $blade | Get-IntersightMoMoRef)
Get-IntersightServerProfile $server | Set-IntersightServerProfile -Action Deploy
```
Reading the documentation, I don't believe the cmdlet supports action to "Activate" the server profile like below:
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/134341388/2a9a64aa-2766-4513-89ce-dd10db413f53)

Is there another command to facilitate activating a server profile?

Thank you,

**Comment by dsoper2** [comment]
The is a ScheduledActions parameter that can be used to Deploy and Active a profile:

$ScheduledActions11 = Initialize-IntersightPolicyScheduledAction -Action "Deploy" -ObjectType "PolicyScheduledAction" -ClassId "PolicyScheduledAction"
$ScheduledActions21 = Initialize-IntersightPolicyScheduledAction -Action "Activate" -ProceedOnReboot $true -ObjectType "PolicyScheduledAction" -ClassId "PolicyScheduledAction"

$mo1 = $getMo1 | Set-IntersightServerProfile -ScheduledActions @($ScheduledActions11,$ScheduledActions21)

A full example is posted at https://github.com/CiscoDevNet/intersight-powershell-utils/blob/main/profile-examples/deploy-activate-server-profile.ps1

**Comment by ivacuna** [comment]
ah, I missed this example, thank you much appreciated
