### ISSUE TITLE
ECDSA signing is supported only on NETCOREAPP3_0 and above

### ISSUE THREAD

**Issue by ThatWindowsGuy** [CiscoDevNet/intersight-powershell#120]
Running Windows 11 22H2 produces the following error when running Get-IntersightManagedObject:

Get-IntersightManagedObject: ECDSA signing is supported only on NETCOREAPP3_0 and above

intersight-powershell/src/GenericCmdlet/HttpSigningAuth.cs

(NETCOREAPP3_0 || NETCOREAPP3_1 || NET5_0)

The above file seems to show that it does not support NETCOREAPP 6, which seems to be the default available on the OS, or at least what is installed with the latest PowerShell 7 (7.3.6)

**Comment by Ghufz** [comment]
This fix will be available in coming release  1.0.11-13683  or later release.
