### ISSUE TITLE
Get-IntersightTamAdvisoryInstance does not return AffectedObject.Name

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/intersight-powershell#123]
Get-IntersightTamAdvisoryInstance does not return AffectedObject.Name when expanding AffectedObject.

(Get-IntersightTamAdvisoryInstance -Expand AffectedObject).Results 

AffectedObject       : class MoBaseMoRelationship {
                         ActualInstance: class MoBaseMo {
                         ClassId: ComputeRackUnit
                         ObjectType: ComputeRackUnit
                         AccountMoid: 636d24f77564612d3375a70e
                         CreateTime: 9/20/2023 2:27:21 PM
                         DomainGroupMoid: 636d24f77564612d3375a70f
                         ModTime: 9/20/2023 2:27:30 PM
                         Moid: 650b014961767535015d7fca
                         Owners: System.Collections.Generic.List`1[System.String]
                         SharedScope: 
                         Tags: System.Collections.Generic.List`1[Intersight.Model.MoTag]
                         VersionContext: 
                         Ancestors: System.Collections.Generic.List`1[Intersight.Model.MoBaseMoRelationship]
                         Parent: 
                         PermissionResources: System.Collections.Generic.List`1[Intersight.Model.MoBaseMoRelationship]
                         DisplayNames: 
                         AdditionalProperties: System.Collections.Generic.Dictionary`2[System.String,System.Object]
                       }
                       
                       }

![image](https://github.com/CiscoDevNet/intersight-powershell/assets/20821117/a9be61a1-5fb0-4602-83e5-86b58c4d51ae)

**Version used**
1.0.11.13515

**Comment by Ghufz** [comment]
The Name property is available in additional properties. 
```
$result = (Get-IntersightTamAdvisoryInstance -Expand AffectedObject).Results
$result[0].AffectedObject.ActualInstance.AdditionalProperties.Name

```
