### ISSUE TITLE
Assembly conflict with VMware.PowerCLI, causing logins to be impossible

### ISSUE THREAD

**Issue by Jikkelsen** [CiscoDevNet/intersight-powershell#124]
**Describe the bug**
Alright, this is a niche of niche problems, but I am sure others are in the same boat.
Assuming `VMware.PowerCLI` and `Intersight.Powershell` is _installed_ but not yet loaded into memory (as if a completely new powershell session is opened):

* If `VMware.PowerCLI`, and submodule `VMware.VimAutomation.Core` (and surely others) have been imported into the runspace _before _ importing `Intersight.Powersahell`, then  `Set-IntersightConfiguration` is unable to run, and will fail with unrelated error "Error performing this operation. Check that BasePath and API Key identifier are configured correctly using the Set-IntersightConfiguration cmdlet. Login fail"
* If running `Set-IntersightConfiguration` before running `import-module VMware.PowerCLI`, then the latter will throw error "Assembly with same name is already loaded", but will then work fine. 

**To Reproduce**
Steps to reproduce the behavior
Assuming `VMware.PowerCLI` and `Intersight.Powershell` is _installed_ but not yet loaded into memory

In one powershell instance, run below:

```

# ---- Connect intersight first ----
# Run this is a fresh Powershell session
# Provide your own $ApiKeyID, $ApiKeyFilePath and $Intersight variable

Get-Module

$onprem = @{
    BasePath             = "https://$Intersight"                           
    ApiKeyId             = $ApiKeyID                                       
    ApiKeyFilePath       = $apikeyfilepath                                 
    HttpSigningHeader    = @('(request-target)', 'Host', 'Date', 'Digest') 
    SkipCertificateCheck = $true                                           
}

Write-Host "Logging in without VMware.VimAutomation.Core loaded"
Set-IntersightConfiguration @onprem
if ($?) {write-host "login success" -ba green -fo black} else {Write-Host "Login fail"}
Get-module

Write-Host "Importing Vmware.VimAutomation.Core"
Import-module Vmware.VimAutomation.Core
if ($?) {write-host "OK"}
Get-module

Write-Host "Logging in again, with VMware.VimAutomation.Core loaded"
Set-IntersightConfiguration @onprem
if ($?) {write-host "login success" -ba green -fo black} else {Write-Host "Login fail"}
Get-Module
```

And in another powershell session run below:

```
# ---- import module first ----
# Run this is a fresh Powershell session
# Provide your own $ApiKeyID, $ApiKeyFilePath and $Intersight variable


Get-Module

$onprem = @{
    BasePath             = "https://$Intersight"                           
    ApiKeyId             = $ApiKeyID                                       
    ApiKeyFilePath       = $apikeyfilepath                                 
    HttpSigningHeader    = @('(request-target)', 'Host', 'Date', 'Digest') 
    SkipCertificateCheck = $true                                           
}

Write-Host "Importing Vmware.VimAutomation.Core"
Import-module Vmware.VimAutomation.Core
if ($?) {write-host "OK"}
Get-module

Write-Host "Logging in with VMware.VimAutomation.Core loaded first"
Set-IntersightConfiguration @onprem
if ($?) {write-host "login success" -ba green -fo black} else {Write-Host "Login fail"}
Get-module

```

**Version used**
 - Intersight PowerShell Module version?

```
Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      11     13515
1      0      11     12561
```

 - Intersight Appliance Version (if using an Intersight Appliance as target)
1.0.9-590

**Expected behavior**
Logging in, without having to juggle modules

**Screenshots**

Screenshot of issues above
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/22538066/3bfdcdee-7dfe-4bfc-a482-aa2a40da58f4)

**Additional context**
Please contact me, if you need further information. I'll gladly jump in a call :)

**Comment by Wajiddat18c** [comment]
I've encountered a similar issue and can confirm the behavior described. It seems that there is indeed a conflict between importing the `VMware.PowerCLI` module and the `Intersight.Powershell` module, leading to unexpected errors when setting the Intersight configuration.

**Comment by Hektodar** [comment]
I have experienced the same issue when trying to connect to intersight!

**Comment by wgjhstt247** [comment]
Same for me here. I started seeing the issue as written in #106 , but didn't try loading just the `Intersight.Powershell` module. When I only import the latest version of `Intersight.Powershell`, `Set-IntersightConfiguration` throws no error for me.

`VMware.PowerCLI` and `Intersight.Powershell` seems to work fine together up to version 1.0.11.12738. After that version, `Set-IntersightConfiguration` no longer works properly.

Try using version 1.0.11.12738 until this is resolved.

Separately, the API in Appliance version 1.0.9-590 is API version 1.0.11.11765. You should be using this `Intersight.Powershell` version with your appliance, until it's upgraded to the latest version: [v1.0.11.11765](https://github.com/CiscoDevNet/intersight-powershell/releases/tag/v1.0.11.11765)

**Comment by Jikkelsen** [comment]
Hiya @wgjhstt247 - thank you for your message! 

Great comment, thank you. 

> Separately, the API in Appliance version 1.0.9-590 is API version 1.0.11.11765.

Interesting, that could indeed be the cause of some of my trouble. Where do I verify this Appliance/API combo? I would love to always tie my API version to the right Appliance version

**Comment by wgjhstt247** [comment]
@Jikkelsen 

Here's one way: Browse to https://<appliance_fqdn>/apidocs . Then click the **API Reference** tab at the top. On the left, you'll see **API Reference v1.0.11-11765**. This could change when the appliance is upgraded.

Another way, is to browse to https://<appliance_fqdn>/apidocs and click the **Downloads** tab. Download the **Intersight OpenAPI YAML format** document by clicking the download icon. Open the file and look at the API version in the file near the top.

**Comment by Jikkelsen** [comment]
Hello again friend. I has been some time since I have last had propper time to test this. 

Both **API Reference** and **Downloads tab** point to `v1.0.11-13165` which leaves me even more confused, because it lands smack in the middle of `v1.0.11.13010` and `v1.0.11.13236`, which are the two nearest releases I can find online. I am sure my reference is either deprecated, or part of some shenanigans since I am on the on-prem solution. 

Ill try to downgrade to `v1.0.11.13010` and see what happens.

**Comment by briamorr** [comment]
It seems to be a conflict between VMware PowerCLI using JsonSubTypes Version=1.8.0.0 and the Intersight Module having the newer 2.0.1.0

Copying the newer dll from the Intersight modules directory to the VMware modules seems to work (but who knows what it breaks on the VMware side)
```
copy "C:\Users\demouser\Documents\PowerShell\Modules\Intersight.PowerShell\1.0.11.14968\JsonSubTypes.dll" "C:\Users\demouser\Documents\PowerShell\Modules\VMware.VimAutomation.Common\13.2.0.22643733\netcoreapp3.1\JsonSubTypes.dll"
```

And then the following works in the same session:
```
Import-module -name VMware.PowerCLI
Connect-VIServer x.y.z.x -Force
Get-VM

Import-module -name Intersight.Powershell
$ApiParams = @{
BasePath = "https://www.Intersight.com"
ApiKeyId = "x/y/z"
ApiKeyFilePath = $pwd.Path + "\SecretKey.txt"
HttpSigningHeader = @("(request-target)", "Host", "Date", "Digest")
}

Set-IntersightConfiguration @ApiParams
Get-IntersightNTPPolicy

**Comment by Ghufz** [comment]
Follow the workaround https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4

**Comment by Ghufz** [comment]
VmWare modules are WindowsPowerShell compatible 
we can use the module to load into WindowsPSSession to avoid the conflict.
```powershell
Import-Module -Name Vmware.VimAutomation.Core  -UseWindowsPowerShell
```
