### ISSUE TITLE
How to power off a blade server

### ISSUE THREAD

**Issue by ivacuna** [CiscoDevNet/intersight-powershell#138]
In UCS Central, we could power off a blade server with command below:
`$serverProfile | set-ucscentralserverpower -state "down" -force`

Can you provide the equivalent syntax for Intersight? I've scoured the Github documentation, examples, and help files and can't seem to figure it out.

We are using version 1.0.11.14628.

Thank you,

**Comment by briamorr** [comment]
This should work:

$serverSettings =  Get-IntersightComputeServerSetting -Name 'myblade-1-4'
$serverSettings | Set-IntersightComputeServerSetting -AdminPowerState "PowerOff"

**Comment by ivacuna** [comment]
awesome, that worked, thanks!
