### ISSUE TITLE
Does New-IntersightServerProfile support deriving from a template?

### ISSUE THREAD

**Issue by odmattw** [CiscoDevNet/intersight-powershell#144]
I'm just getting started with this and I figured there would be a way to specify a template when generating server profiles.  Does anyone know if that is supported?

**Comment by briamorr** [comment]
Are you looking to derive a profile from a server profile template?  If so something like this should work

```
$source = Get-IntersightServerProfileTemplate -Name "IMM-template"

$orgRef = Get-IntersightOrganizationOrganization -Name default

$targetProfile = Initialize-IntersightServerProfile -Name IMM-profile1 -Description "derived from template" -Organization (Get-IntersightMoMoRef -ManagedObject ($orgRef))

New-IntersightBulkMoCloner -Sources $source -Targets $targetProfile

**Comment by odmattw** [comment]
Thanks.  I found an example where they did something similar and I got it working.  I just assumed when I was browsing the available cmdlets that this one would support deriving from a template.
