### ISSUE TITLE
Community Forum for General Assistance

### ISSUE THREAD

**Issue by tbrock47** [CiscoDevNet/intersight-powershell#150]
Can someone please point me to a community forum for intersight-powershell where users can pose general questions about using the module.

I periodically have questions about how to do something and I feel like posting a question as an **Issue** in the repository is not the best place to seek general assistance. The repo should be reserved for actual code issues and bugs, not user support.

**Comment by Ghufz** [comment]
Hi @tbrock47 
You may raise your question as an issue, we keep track of the issues and mark it if it qualify for bug or enhancement
