### ISSUE TITLE
1.0.11-17227 doesn't exist in powershell gallery

### ISSUE THREAD

**Issue by wgjhstt247** [CiscoDevNet/intersight-powershell#153]
**Describe the bug**
1.0.11-17227 doesn't exist in powershell gallery, but it's the latest release

**To Reproduce**
Steps to reproduce the behavior
- PowerShell code snippet (when possible)

**Version used**
 - Intersight PowerShell Module version?
 - Intersight Appliance Version (if using an Intersight Appliance as target)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Ghufz** [comment]
We are facing issue with module update due  to signing issue, that is why Intersight.PowerShell v1.0.11.17227 is not available in PowerShell gallery. we are working on it to publish the same to PowerShell gallery

**Comment by Ghufz** [comment]
Latest PowerShell module is published to PSGallery 1.0.11.17412
