### ISSUE TITLE
Trigger Fabric evacuation via API call

### ISSUE THREAD

**Issue by zj-92** [CiscoDevNet/intersight-powershell#156]
Looking at `Set-IntersightNetworkElement`, I see no parameter for adjusting the AdminEvacState or OperEvacState. 

Are there any `-AdditionalProperties` values that can be passed to `Set-IntersightNetworkElement` that would allow for triggering Fabric Evacuation programmatically?

**Comment by briamorr** [comment]
On module 1.0.11.17412 this should work:

```
$fabricInterconnects = (Get-IntersightEquipmentSwitchOperation -Expand NetworkElement).Results

foreach($fi in $fabricInterconnects)
{
	if($fi.NetworkElement.ActualInstance.Serial -eq 'FDO123456')
	{
	  $fi | Set-IntersightEquipmentSwitchOperation -AdminEvacState 'Enabled'
	}
}

**Comment by zj-92** [comment]
Fantastic; I completely missed that one. Thanks!

> On module 1.0.11.17412 this should work:
> 
> ```
> $fabricInterconnects = (Get-IntersightEquipmentSwitchOperation -Expand NetworkElement).Results
> 
> foreach($fi in $fabricInterconnects)
> {
> 	if($fi.NetworkElement.ActualInstance.Serial -eq 'FDO123456')
> 	{
> 	  $fi | Set-IntersightEquipmentSwitchOperation -AdminEvacState 'Enabled'
> 	}
> }
> ```
