### ISSUE TITLE
Get-IntersightServerProfile discrepancy 

### ISSUE THREAD

**Issue by safabianb1991** [CiscoDevNet/intersight-powershell#157]
**Describe the bug**
Get-IntersightServerProfile  | Select-Object Name | ?{$_.Name -eq "NameOfTheProfile"} the profile is not visible. But if i use the following method, i getting all the information. 

Get-IntersightServerProfile -Name NameOfTheProfile | Select-Object Name

**To Reproduce**
Steps to reproduce the behavior
- PowerShell code snippet (when possible)

**Version used**
 - Intersight PowerShell Module version?
Name              : Intersight.PowerShell
Path              : C:\Program Files\WindowsPowerShell\Modules\Intersight.PowerShell\1.0.11.17412\Intersight.PowerShell.psd1
Description       : Intersight Powershell module provides the cmdlets to manage, analyze, and automate the IT infrastructure in Intersight.
ModuleType        : Binary
Version           : 1.0.11.17412
 - Intersight Appliance Version (if using an Intersight Appliance as target)
1.0.9-675
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by briamorr** [comment]
If you check the output of Get-IntersightServerProfile -Count $true do you have more than 100 profiles?  If so, you can try specifying the $top command up to a maximum of 1000 objects:

```
Get-IntersightServerProfile -Top 1000 | Select-Object -Expand Results | Select Name | ?{$_.Name -eq "NameOfTheProfile"}
```

If you have more than 1000 profiles you will then need to paginate the requests or use server side filtering like you had done with -Name

**Comment by safabianb1991** [comment]
Great, thanks, it is now OK!
