### ISSUE TITLE
How to query more then 1000 ComputeBlades with Get-IntersightComputeBlade

### ISSUE THREAD

**Issue by rfiodv** [CiscoDevNet/intersight-powershell#166]
Hi,

we have the issue, that have more then 2500 Blades in Intersight.
We are now faced with the challenge of, how we can query all blades so that we can loop cleanly.

Get-IntersightComputeBlade -Top is maxed at 1000.

Do you have any ideas on how we can solve this? 

Best regards,
Ricardo

**Comment by vvb** [comment]
There is an example here - https://github.com/CiscoDevNet/intersight-powershell-utils/blob/main/pagination-examples/auditlog-pagination.ps1

**Comment by sandkum5** [comment]
Here is an example

```
$Servers = [System.Collections.ArrayList]@()
$skip = 0
$count = 0
$totalCount = (Get-IntersightComputePhysicalSummary -Count $true).Count

while ($count -le $totalCount){
    $Servers += (Get-IntersightComputePhysicalSummary -Top 1000 -Skip $skip).Results
    $skip += 1000
    $count += 1000
}
```

**Comment by rfiodv** [comment]
It worked, thank you !
