### ISSUE TITLE
"Set-IntersightServerProfile -SrcTemplate $null" no longer working

### ISSUE THREAD

**Issue by tbrock47** [CiscoDevNet/intersight-powershell#168]
**Describe the bug**
Unable to remove Server Profile Template from Server Profile using Set-IntersightServerProfile.

**To Reproduce**
Steps to reproduce the behavior
```
$IntersightServerProfile = Get-IntersightServerProfile -Name $ServerProfileName
$IntersightServerProfile | Set-IntersightServerProfile -SrcTemplate $null
ERROR: Set-IntersightServerProfile: Object serialized to Array. JObject instance expected.
```

**Version used**
 - Intersight PowerShell Module version (1.0.11.17956)

**Expected behavior**
"$IntersightServerProfile | Set-IntersightServerProfile -SrcTemplate $null" used to remove the Server Profile Template from the requested profile, but no longer appears to work. Unsure what may have changed.

**Screenshots**
![image](https://github.com/user-attachments/assets/5deec037-2c40-412e-90ba-019d1ccdb65f)

**Additional context**
Appears to only be an issue when piping the object as the following appears to work.
`Set-IntersightServerProfile -Moid $IntersightServerProfile.Moid -SrcTemplate $null`

**Comment by Ghufz** [comment]
It is bug will work on it,
Here is workaround to accomplish above configuration

```powershell
$result = $IntersightServerProfile | Set-IntersightManagedObject -AddtionProperties @{"SrcTemplate"=$null} | ConvertFrom-Json

```

**Comment by Ghufz** [comment]
The issue has been addressed in the latest release https://www.powershellgallery.com/packages/Intersight.PowerShell/1.0.11.18775
