### ISSUE TITLE
No longer able to add policies using PolicyBucket.Add() on UCS Server Profile (CIMC)

### ISSUE THREAD

**Issue by mdk85-start** [CiscoDevNet/intersight-powershell#169]
**Describe the bug**
I am seeing issues while adding a new existing policy on existing an ucs server profile for cimc, where $serverProfile.policyBucket.Add method doesn't execute. 

When i ran this code couple of weeks it was able to attach the policy into UCS Server Profile (~200) . But now it doesn't execute. 

Also when i run Set-IntersightServerProfile, I am seeing the following error

Code - $serverProfileKVM = $serverProfileDetail | Set-IntersightServerProfile 

"Set-IntersightServerProfile: Object serialized to Array. JObject instance expected"

**To Reproduce**
Steps to reproduce the behavior

        

       
        $org = Get-IntersightOrganizationOrganization -Name "default"
        $kvmPolicy = Get-IntersightKvmpolicy -Name "base:base:base:global:base:01" -Organization $org

        $serverProfileDetail = Get-IntersightServerProfile -Name $serverProfile -Organization $org
        $serverProfileName = $serverProfileDetail.Name
        $serverProfileDetail.PolicyBucket.Add($kvmPolicy)

        $ScheduledActions11 = Initialize-IntersightPolicyScheduledAction -Action "Deploy"
        $ScheduledActions21 = Initialize-IntersightPolicyScheduledAction -Action "Activate" -ProceedOnReboot $false

        $serverProfileKVM = $serverProfileDetail | Set-IntersightServerProfile 
        $serverProfileKVM | Set-IntersightServerProfile -ScheduledActions @($ScheduledActions11, $ScheduledActions21) -Action "Deploy" | Out-Null**

**Version used**
 - 
    Intersight PowerShell Module version (1.0.11.17956)

**Expected behavior**
Add additional policies into UCS Server Profile

**Screenshots**
![image](https://github.com/user-attachments/assets/366af435-f7a7-4fc4-bd05-11d3fc7abd4d)

**Additional context**

**Comment by Ghufz** [comment]
Please use your script with latest released module version https://www.powershellgallery.com/packages/Intersight.PowerShell/1.0.11.18775

**Comment by mdk85-start** [comment]
@Ghufz : the new module fixed the issue. Thanks for fixing the resolution quickly! :)

**Comment by mdk85-start** [comment]
Using contain() method in PolicyBucket, how do i find a policy inside $serverProfile.PolicyBucket.Contain() ?

**Comment by Ghufz** [comment]
PolicyBucket is complex type so contains will not solve your issue,
either use compare-object cmdlet, or simply iterate on policy bucket and check
