### ISSUE TITLE
module not visible after install-module from psgallery

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/intersight-powershell#19]
DevNet reported issue that I duplicated on my mac running PS core 7.1.3 where an install from gallery isn't available until get-command is run:

install-module -name intersight.powershell
(restart powershell)
get-module -name intersight.powershell
(no output)
get-command -module intersight.powershell
...
Cmdlet          Set-IntersightWorkflowWorkflowDefinition           1.0.9.4403 Intersight.PowerShell
Cmdlet          Set-IntersightWorkflowWorkflowInfo                 1.0.9.4403 Intersight.PowerShell
get-module -name intersight.powershell   
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.9.4403            Intersight.PowerShell               {Get-IntersightAaaAuditRecord,

**Comment by Ghufz** [comment]
Get-module will return null if the specified module is not loaded.

After installing it from PSGallery using the below cmdlet

```powershell
Install-Module -Name Intersight.PowerShell
```
Either user need to use any of the cmdlet from that module or manually import the module like below
```powershell
Import-Module -Name Intersight.PowerShell
``` 

after peforming above step 

```powershell
Get-Moudle -Name Intersight.PowerShell 
```
should show the output with loaded module details. 
Let me know if I missed something.

**Comment by Ghufz** [comment]
This issue has been fixed in following PR 
https://github.com/CiscoDevNet/intersight-powershell/pull/22
