### ISSUE TITLE
The module manifest should specify the cmdlets to export instead of using a wildcard

### ISSUE THREAD

**Issue by MartinGC94** [CiscoDevNet/intersight-powershell#20]
By explicitly specifying the commands this module exports in the module manifest, PowerShell command discovery will be able to find the commands without first importing the module. This means a user will be able to tab complete the command names or run Get-Command without first importing the module.

You are already using a PowerShell script to build the module package so a quick and simple way to do this is to import the .dll right after building it and running Get-Command and then use that data to update the module manifest. Another option is to analyze the source files/compiled dll file with roslyn/reflection to find the public cmdlet classes.

**Comment by Ghufz** [comment]
This issue has been fixed in following PR
https://github.com/CiscoDevNet/intersight-powershell/pull/22
