### ISSUE TITLE
v3 API keys (ECDSA) not supported

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/intersight-powershell#3]
Current ECDSA code is not working on Windows 2012 R2 PowerShell 7.0.3 and will not work on Linux/Mac where ECDSACng is not available.

**Comment by sebastien-rosset** [comment]
What is the issue exactly? Are you asking for the ability to expose all the key generation details in the Intersight UI? The Intersight **API** already supports many options including RSA-PSS, RSASSA-PKCS, ECDSA, Ed25519. Giving the choice increases the likelihood a larger number of client platforms are supported, but the platform also needs to be up-to-date to ensure it meets security guidelines.

**Comment by dsoper2** [comment]
Here are signing params for a Windows host and version info:

PS C:\Users\Administrator\Documents\intersight-powershell-1> $httpSigningParams= @{      
>>    KeyId = "596cc..."
>>    KeyFilePath = "\Users\Administrator\Downloads\SecretKey.txt"
>>    HttpSigningHeader = @("(request-target)","Host","Date","Digest")
>>    HashAlgorithm = "sha256"
>> }
PS C:\Users\Administrator\Documents\intersight-powershell-1> Set-IntersightConfigurationHttpSigning @httpSigningParams
PS C:\Users\Administrator\Documents\intersight-powershell-1> Get-IntersightWorkflowWorkflowInfoByMoid -moid 5f455712696f6e2d31505bfe
Invoke-WebRequest: C:\Users\Administrator\Documents\intersight-powershell-1\src\Intersight\Private\IntersightApiClient.ps1:126
Line |
 126 |          $Response = Invoke-WebRequest -Uri $UriBuilder.Uri `
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |

I added debug to see that was a 401 unauthorized - ideally the SDK would catch exceptions and provide debug output.

PS C:\Users\Administrator\Documents\intersight-powershell-1> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

On Linux or Mac, nothing would currently work due to use of Cng for RSA and ECDSA (which is only supported on Windows platforms).

**Comment by Ghufz** [comment]
The issue with ECDSA signature has been fixed by the PR : https://github.com/CiscoDevNet/intersight-powershell/pull/6
```powershell
PS C:\> Get-IntersightConfigurationHttpSigning

HashAlgorithm     : sha256
KeyId             : xxxxxxx3c06/5f21c9d97564612d30dd575a/5f585b2a7564612dxxxxxxxxx
SigningAlgorithm  :
HttpSigningHeader : {(request-target), Host, Date, Digest}
KeyFilePath       : C:\Users\admin\Downloads\PowerShellSDKV3.txt

PS C:\> $s = Get-IntersightSolPolicyList

PS C:\> $s.ActualInstance.Results[0]

Moid                : 5f59b4236275722d30d0ca6d
ObjectType          : sol.Policy
ClassId             : sol.Policy
CreateTime          : 10-09-2020 05:05:39
ModTime             : 10-09-2020 05:05:39
Tags                : {}
Owners              : {5f21c2527564612d30dd3c06}
SharedScope         :
AccountMoid         : 5f21c2527564612d30dd3c06
DomainGroupMoid     : 5f21c2527564612d30dd3c07
Ancestors           : {}
PermissionResources : {@{ObjectType=organization.Organization; ClassId=mo.MoRef; Moid=5f21c8936972652d30c05046;
                      link=https://intersight.cisco.com/api/v1/organization/Organizations/5f21c8936972652d30c05046}}
Description         : Test_SOL
Name                : Test_Sol
BaudRate            : 9600
ComPort             : com0
Enabled             : True
SshPort             : 1080
Organization        : @{ObjectType=organization.Organization; ClassId=mo.MoRef; Moid=5f21c8936972652d30c05046;
                      link=https://intersight.cisco.com/api/v1/organization/Organizations/5f21c8936972652d30c05046}
Profiles            : {}



```
