### ISSUE TITLE
Cannot configure Intersight and connect to API

### ISSUE THREAD

**Issue by curelesc** [CiscoDevNet/intersight-powershell#32]
Hello Team.
We want to connect to the Cisco Intersight API (to run some powershell commands), and we receive an error
We are not running Cisco Intersight on-premises, and we have and Essentials license

We've followed the documentations from here :
https://github.com/CiscoDevNet/intersight-powershell-utils

And executed the powershell command (after upgrading to powershell 7.2 as required for prerequisites, and imported the Cisco Intersight Module, and also generated the api key from Intersight)

Set-IntersightConfiguration: E:\CPT_Team\Bog\Intersight\api-config.ps1
:39
Line |
39 | Set-IntersightConfiguration @ApiParams
| ~~~~~~~~~~
| A parameter cannot be found that matches parameter name
| 'HttpSingingHeader'.

That's the error that we are receiving after running the "api-config.ps1".

Is it possible to give us a hand here?

Also we want to do that, because we want to discover if we can automatically export on a daily basis the RMA history for the servers (SN)

**Comment by Ghufz** [comment]
Hi Curelesc

Please use the below script snippet to configure Intersight environment 

```powershell
$staging = @{
    BasePath = "https://intersight.com"
    ApiKeyId = "xxxxxxxxxxxxxxxxx/5ee095397564612d31a62c01/xxxxxxxxxxxxxxxxxxxxxx"
    ApiKeyFilePath = "C:\Users\Downloads\SecretKey.txt" 
    HttpSigningHeader =  @("(request-target)", "Host", "Date", "Digest")
}

Set-IntersightConfiguration @staging

```
or you can use the script 
https://github.com/CiscoDevNet/intersight-powershell-utils
I have fixed the parameter name in the script.

**Comment by curelesc** [comment]
Thanks a lot Ghufz!
It works
Now after i run a intersight command (various), i receive this error :

Get-IntersightDeviceconnectorPolicy: Error calling GetDeviceconnectorPolicyList:
 The SSL connection could not be established, see inner exception.

**Comment by Ghufz** [comment]
Okay, So you on-prem does have valid SSL certificate. 
You can skip the certificate check by using the -SkipCertificateCheck parameters.
while configuring the Intersight environment.

```powershell
$staging = @{
    BasePath = "https://xyz.com"
    ApiKeyId = "xxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxx"
    ApiKeyFilePath = "C:\Users\Downloads\SecretKey.txt" 
    HttpSigningHeader =  @("(request-target)", "Host", "Date", "Digest")
    SkipCertificateCheck = $true
}

Set-IntersightConfiguration @staging

```

**Comment by curelesc** [comment]
Hmmm. Strange. After i've added your parameter, is still gives me the same error...

**Comment by Ghufz** [comment]
Are you able to run other Get cmdlets ? if you face the error for all cmdlets then can you re-launch the powershell host and do the configuration

**Comment by curelesc** [comment]
We are not running on-premises. We are using it through the Device Connector

**Comment by Ghufz** [comment]
Can you explain little bit, what is using through device connector means?

Are you able to create a policies using on the intersight GUI using the same user name for which you have created the API key?

Can you provide the below details.

OS platform:- 
Cloud environment :- Intersight.com/on-premise ?

Are you targeting to the same intersight where you have created API key or different one ?

**Comment by curelesc** [comment]
We are using a custom link : https://5d1662e07564612d3043096a.intersight.com/
We are using the cloud version, not the appliance on-premises
Thanks a lot!

**Comment by Ghufz** [comment]
Hi,
Are you still facing the issue ?

**Comment by curelesc** [comment]
Hello @Ghufz !
Thanks for all the help provided! 
We've gave up on Intersight, because it didn't serve our requirements. We solved our need through the Cisco API Console.
