### ISSUE TITLE
Get-IntersightSearchTagItem Returns Error "The JSON String incorrectly matches more than one schema (should be exactly one match): System.Collections.Generic.List`1[System.String]"   [Backend: INTERSIGHT-13763]

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-powershell#34]
Get-IntersightSearchTagItem Returns Error

Intersight.PowerShell 1.0.9.5313  

`
Get-IntersightSearchTagItem -Filter "Moid eq '61a76ab276752d3132064103'"
Get-IntersightSearchTagItem: The JSON string `{
  "ObjectType": "search.TagItem.List",
  "Count": 2,
  "Results": [
    {
      "Key": "Intersight.LicenseTier",
      "Count": 2,
      "Values": [
        "Premier"
      ]
    },
    {
      "Key": "OS",
      "Count": 2,
      "Values": [
        "Linux"
      ]
    }
  ]
}` incorrectly matches more than one schema (should be exactly one match): System.Collections.Generic.List`1[System.String]`

**Comment by Ghufz** [comment]
@[briamorr](https://github.com/briamorr)
In such case we have workaround as below
```powershell
$result = Get-IntersightSearchTagItem -Moid "" -Json | ConvertFrom-Json
```

**Comment by vvb** [comment]
This looks like an Intersight backend issue to me. The `ClassId` property is missing in the response and that makes PowerShell throw this error. @Ghufz - let us check the response on this one.

**Comment by Ghufz** [comment]
here is the work around for the reported issue.

```powershell
$result = Get-IntersightManagedObject -objectType search.TagItem -Filter "Moid eq '61a76ab276752d3132064103'" | ConvertFrom-Json
$serachItems = $result.Results
```
