### ISSUE TITLE
too many properties returned when using -select parameter

### ISSUE THREAD

**Issue by dchosnek** [CiscoDevNet/intersight-powershell#36]
Unlike the API, the SDK seems to be returning many empty parameters when the `-Select` statement is used. This is problematic for items like dates, which it attempts to display as `1/1/0001 12:00:00 AM` or for nested objects, which it displays as an empty object `{ }`. This is misleading.

When I retrieve the list of Alarms through the API browser and specify `$select Moid`, I only get back ClassId, ObjectId, and Moid (which is what I would expect).

```
  "Results": [
    {
      "ClassId": "cond.Alarm",
      "Moid": "5c8014c865696e2d306522d2",
      "ObjectType": "cond.Alarm"
    },
.
.
.
```

Using the SDK, when I run  `(Get-IntersightCondAlarm -Select Moid).Results`, I many empty properties:

```
ClassId               : CondAlarm
ObjectType            : CondAlarm
Acknowledge           : 
OrigSeverity          : 
Severity              : 
AcknowledgeBy         : 
AcknowledgeTime       : 1/1/0001 12:00:00 AM
AffectedMoDisplayName : 
AffectedMoId          : 
AffectedMoType        : 
AffectedObject        : 
AncestorMoId          : 
AncestorMoType        : 
Code                  : 
CreationTime          : 1/1/0001 12:00:00 AM
Description           : 
LastTransitionTime    : 1/1/0001 12:00:00 AM
MsAffectedObject      : 
Name                  : 
AffectedMo            : 
RegisteredDevice      : 
AdditionalProperties  : {}
AccountMoid           : 
CreateTime            : 1/1/0001 12:00:00 AM
DomainGroupMoid       : 
ModTime               : 1/1/0001 12:00:00 AM
Moid                  : 608814df65696e2d30de0ce1
Owners                : 
SharedScope           : 
Tags                  : 
VersionContext        : 
Ancestors             : 
Parent                : 
PermissionResources   : 
DisplayNames          : 
```

For consistency and clarity, it should only return ClassId, ObjectId, Moid, and any additional parameters that I have requested.

**Comment by Ghufz** [comment]
(Get-IntersightCondAlarm -Select Moid).Results returns the extra properties due to c# object. 
To avoid the extra property please use -json switch parameter, it provides only those properties which API returns

```powershell
$result = Get-IntersightCondAlarm -Select Moid -Json | ConvertFrom-Json
$result.Results
```
