### ISSUE TITLE
secretKey typo

### ISSUE THREAD

**Issue by shaneschnell** [CiscoDevNet/intersight-powershell#40]
There are typos on lines 146 and 156.

secrectKey.txt should be secretKey.txt

https://github.com/CiscoDevNet/intersight-powershell/blob/e70bb64bda7cdf9f3ec22b479880a202e50f7626/README.md?plain=1#L146
https://github.com/CiscoDevNet/intersight-powershell/blob/e70bb64bda7cdf9f3ec22b479880a202e50f7626/README.md?plain=1#L156

**Comment by Ghufz** [comment]
Corrected the typos 
https://github.com/CiscoDevNet/intersight-powershell/pull/41
