### ISSUE TITLE
Missing inner exception information when SSL connection fails

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-powershell#55]
Missing inner exception information when SSL connection fails (for example untrusted self signed certificate on CVA/PVA).  This makes it difficult to troubleshoot what the issue is.

PS C:\Users\demouser\Downloads> Get-IntersightCondAlarm -Debug
Get-IntersightCondAlarm: Error calling GetCondAlarmList: The SSL connection could not be established, see inner exception.

Repro:
Intersight VA with self signed or untrusted certs

$ApiParams = @{
BasePath = "https://myvirtualappliance.local"
ApiKeyId = "xxxx/yyy/zzzz"
ApiKeyFilePath = $pwd.Path + "\SecretKey.txt"
HttpSigningHeader = @("(request-target)", "Host", "Date", "Digest")
}

Set-IntersightConfiguration @ApiParams -SkipCertificateCheck
Get-IntersightCondAlarm

**Comment by Ghufz** [comment]
dotnet framework does not throws any inner exception SSL failure.

Please specify the -SkipCertificateCheck as below

```
$ApiParams = @{
BasePath = "https://myvirtualappliance.local/"
ApiKeyId = "xxxx/yyy/zzzz"
ApiKeyFilePath = $pwd.Path + "\SecretKey.txt"
HttpSigningHeader = @("(request-target)", "Host", "Date", "Digest")
SkipCertificateCheck = $true
}

Set-IntersightConfiguration @ApiParams 
Get-IntersightCondAlarm
```
