### ISSUE TITLE
Get-IntersightVnicEthIfInventory with Error: incorrectly matches more than one schema [Backend: INTERSIGHT-12354]

### ISSUE THREAD

**Issue by stastka** [CiscoDevNet/intersight-powershell#56]
I have by Cmdlet **Get-IntersightVnicEthIfInventory** following Error: 

incorrectly matches more than one schema (should be exactly one match): System.Collections.Generic.List`1[System.String]

What i not understand how can i filter out to split the Object who has different schemas. 

I try but output is very strange:

```
Get-IntersightVnicEthIfInventory -count 1 -top 1 -skip 1 | fl

AdditionalProperties : {}
Count                : 8
ObjectType           : mo.DocumentCount
```

Version: intersight-powershell-1.0.9.6484

**Comment by Ghufz** [comment]
More than one schema macthes exception has been thrown when any of the MO does not have ObjectType which leads to this exception. Please check for the MO which does not have ObjectType and remove it. 

You can use below cmdlet to get the response from the Intersight and investigate the MO.

```
Get-IntersightManagedObject -ObjectType vnic.EthIfInventory 
```
the result will be in json data. you can pass it to the CO=onvertFrom-Json to get into object form.
