### ISSUE TITLE
Derrive Server Profile from template example

### ISSUE THREAD

**Issue by eminchen** [CiscoDevNet/intersight-powershell#60]
I am not seeing in this help section how to derrive server profile from server profile template, is it supported by PowerShell?

https://github.com/CiscoDevNet/intersight-powershell/blob/master/docs/Set-IntersightServerProfileTemplate.m
<img width="1485" alt="Screen Shot 2022-05-18 at 10 25 22 AM" src="https://user-images.githubusercontent.com/3236958/169065245-2c073693-00bb-4af6-97f8-bbedb0f58d0b.png">
d

**Comment by savithamr** [comment]
Below is the cmdlets example to derive Server Profile from template:

`
$source = Get-IntersightServerProfileTemplate -Name "server_template"

$orgRef = Get-IntersightOrganizationOrganization -Name default

$targetProfile = Initialize-IntersightServerProfile -Name cloned-server-profile -Description "cloned from template" -Organization (Get-IntersightMoMoRef -ManagedObject ($orgRef))

New-IntersightBulkMoCloner -Sources $source -Targets $targetProfile
`
