### ISSUE TITLE
[Enhancement] - Add API Private Key Content Variable

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-powershell#65]
[Enhancement] - Add API Private Key Content Variable

Currently the API private key must be referenced as a file location with:
ApiKeyFilePath = $pwd.Path + "\SecretKey.txt"

It would be useful to be able to have the option to reference the content of the key instead of just a file location, for example:

OS Environment Variable API_PRIVATE_KEY =  "-----BEGIN RSA PRIVATE KEY----- MII -----END RSA PRIVATE KEY-----"

ApiPrivateKey = Get-Variable API_PRIVATE_KEY -valueOnly

**Comment by Ghufz** [comment]
Added the new parameter named KeyString in Set-IntersightConfiguration cmdlet which allows to specify the APIKey content.
This enhancement will be available in the release 1.0.11-13010  or later
