### ISSUE TITLE
Get-IntersightApplianceSystemInfo - incorrectly matches more than one schema

### ISSUE THREAD

**Issue by wgjhstt247** [CiscoDevNet/intersight-powershell#67]
First run `Set-IntersightConfiguration` to configure your connection values for an Intersight Connected Virtual Appliance (CVA)
Then run
```powershell
Get-IntersightApplianceSystemInfo
```
It returns with the error `... incorrectly matches more than one schema (should be exactly one match): ...`

From the error message, I can see that:
`AccountMoid` value is an empty string, `CloudConnStatus` value is an empty string, and `Parent`: `MoId` and `ObjectType` values are empty strings.

Running this:
```powershell 
Get-IntersightManagedObject -ObjectType "appliance.SystemInfo"
``` 
gives me 403 forbidden with Account Administrator rights.

However, 
```powershell
Get-IntersightApplianceSystemInfo -Select "Hostname,Version"
```
works fine.

**Comment by vvb** [comment]
Hi @wgjhstt247 Could you provide us with some more details.
1. Are you executing this command against a connected appliance?
2. What is the version of the onprem appliance being used?
3. What is the version of the Intersight PowerShell Module being used?
4. Could you provide the console output of `Get-IntersightApplianceSystemInfo -WithHttpInfo`

**Comment by wgjhstt247** [comment]
@vvb 
1. Yes. Connected Virtual Appliance
2. 1.0.9-442
3. 1.0.9.6484
4. Same error message appears as running the command without `-WithHttpInfo` - `... incorrectly matches more than one schema (should be exactly one match): ...` and provides no additional text

**Comment by Ghufz** [comment]
try this workaround 

```powershell
$result = Get-IntersightApplianceSystemInfo -Select "Hostname,Version" -Json | ConvertFrom-Json

```
