### ISSUE TITLE
Unable to Import Default Config by Eth- / FC Adapter Policy

### ISSUE THREAD

**Issue by rfiodv** [CiscoDevNet/intersight-powershell#71]
Is there a option to import the "Default Configuration" for Fibre Channel Adapter & Ethernet Adapter via Powershell ?

In the Intersight gui is it possible to import them (see in the pictures).
If you choose on of those policies, the settings will be automatically changed.

Fibre Channel
![image](https://user-images.githubusercontent.com/103107417/181501236-f06e32cc-3677-4e0d-b96d-5954dc478f9e.png)

Ethernet
![image](https://user-images.githubusercontent.com/103107417/181501263-84a8f60e-dad3-4600-b578-3f265fc6dcab.png)

**Comment by savithamr** [comment]
The below methods can be used to create a "Fibre Channel Adapter" policy using the default configuration.
Method 1:
$organization = Get-IntersightOrganizationOrganization -Name 'default'

# Get the default Profile by Name
$def_solaris = Get-IntersightVnicFcAdapterPolicy -Name Solaris

New-IntersightVnicFcAdapterPolicy -Organization $organization -ErrorRecoverySettings $def_solaris.ErrorRecoverySettings -FlogiSettings $def_solaris.FlogiSettings -InterruptSettings $def_solaris.InterruptSettings -PlogiSettings $def_solaris.PlogiSettings -RxQueueSettings $def_solaris.RxQueueSettings -TxQueueSettings $def_solaris.TxQueueSettings -ScsiQueueSettings $def_solaris.ScsiQueueSettings -Name 'fc_adapter_policy' -ErrorDetectionTimeout $def_solaris.ErrorDetectionTimeout -IoThrottleCount $def_solaris.IoThrottleCount -LunCount $def_solaris.LunCount -LunQueueDepth $def_solaris.LunQueueDepth -ResourceAllocationTimeout $def_solaris.ResourceAllocationTimeout

Method 2:
$organization = Get-IntersightOrganizationOrganization -Name 'default'

# Get all the default configurations 
$def_profiles = Get-IntersightVnicFcAdapterPolicy -Filter "(SharedScope eq 'shared')" -Top 25

# To know which configuration to apply
$def_profiles.Results[5].Name
VMWare
 
New-IntersightVnicFcAdapterPolicy -Organization $organization -ErrorRecoverySettings $def_profiles.Results[5].ErrorRecoverySettings -FlogiSettings $def_profiles.Results[5].FlogiSettings -InterruptSettings $def_profiles.Results[5].InterruptSettings -PlogiSettings $def_profiles.Results[5].PlogiSettings -RxQueueSettings $def_profiles.Results[5].RxQueueSettings -TxQueueSettings $def_profiles.Results[5].TxQueueSettings -ScsiQueueSettings $def_profiles.Results[5].ScsiQueueSettings -Name 'fc_adapter_policy' -ErrorDetectionTimeout $def_profiles.Results[5].ErrorDetectionTimeout -IoThrottleCount $def_profiles.Results[5].IoThrottleCount -LunCount $def_profiles.Results[5].LunCount -LunQueueDepth $def_profiles.Results[5].LunQueueDepth -ResourceAllocationTimeout $def_profiles.Results[5].ResourceAllocationTimeout

------------------------------------------------------------------------------------------------
The below method can be used to create an "Ethernet Adapter" policy using the default configuration
$organization = Get-IntersightOrganizationOrganization -Name 'default'

# Get all the default configurations 
$eth_profile = Get-IntersightVnicEthAdapterPolicy -Filter "(SharedScope eq 'shared')" -Top 25

# To know which configuration to apply
$eth_profile.Results[5].Name
Windows
 
New-IntersightVnicEthAdapterPolicy -Organization $organization -VxlanSettings $eth_profile.Results[5].VxlanSettings -NvgreSettings $eth_profile.Results[5].NvgreSettings -ArfsSettings $eth_profile.Results[5].ArfsSettings -InterruptSettings $eth_profile.Results[5].InterruptSettings -CompletionQueueSettings $eth_profile.Results[5].CompletionQueueSettings -RxQueueSettings $eth_profile.Results[5].RxQueueSettings -TxQueueSettings $eth_profile.Results[5].TxQueueSettings -TcpOffloadSettings $eth_profile.Results[5].TcpOffloadSettings -Name 'eth_adapter_policy' -RssSettings $eth_profile.Results[5].RssSettings -UplinkFailbackTimeout $eth_profile.Results[5].UplinkFailbackTimeout

**Comment by rfiodv** [comment]
Thank you ! 
That helped us a lot :)
