### ISSUE TITLE
Example to deploy a created ServerProfile

### ISSUE THREAD

**Issue by rfiodv** [CiscoDevNet/intersight-powershell#72]
Example to deploy a created ServerProfile.

`Set-IntersightServerProfile -Action "Deploy" -Moid $ServerProfileRef` <- won't work.
`Set-IntersightServerProfile: Error calling GetServerProfileByMoid: <!DOCTYPE html>`

![image](https://user-images.githubusercontent.com/103107417/182632044-5178ab0b-0dba-4ad2-9a77-39b90998db61.png)

**Comment by savithamr** [comment]
Below are steps to deploy a created ServerProfile:

Get the ServerProfile by Name
$serverprofile = Get-IntersightServerProfile -name ESXTEST01

$serverprofile | Set-IntersightServerProfile -Action "Deploy"

**Comment by rfiodv** [comment]
Thanks, worked !
