### ISSUE TITLE
IKS VM Infrastructure Provider failing with "NodeGroup" relationship as read-only

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/intersight-powershell#74]
**Describe the bug**
When I am trying to create a Kubernetes Virtual Machine Infrastructure Provider, it fails with an error: 

```
Line |
  24 |  $result = New-IntersightKubernetesVirtualMachineInfrastructureProvide …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error calling CreateKubernetesVirtualMachineInfrastructureProvider: {"code":"InvalidRequest","message":"The request body
     | contains the 'NodeGroup' relationship, which is read-only. Do not include read-only relationships in the request
     | body","messageId":"barcelona_request_cannot_modify_read_only_relationships","messageParams":{"1":"NodeGroup"},"traceId":"rtu2iuAlE2PTMf0V8-4pMBFUftiwCtssVgxedRi2XHbpdULQjcfxEA=="}
```

**To Reproduce**
Steps to reproduce the behavior
- PowerShell code snippet
```
$instanceTypeObject = Initialize-IntersightMoMoRef -ClassId "MoMoRef" -ObjectType "kubernetesVirtualMachineInstanceType" -Selector "Name eq '$($vmInstanceName)'"

$infraConfigPolicyObject = Initialize-IntersightMoMoRef -ClassId "MoMoRef" -ObjectType "kubernetesVirtualMachineInfraConfigPolicy" -Selector "Name eq '$($infraConfigPolicyName)'"

$nodeGroupObject = Initialize-IntersightMoMoRef -ClassId "MoMoRef" -ObjectType "kubernetesNodeGroupProfile" -Selector "Name eq '$($nodeGroupName)'"

# Create Virtual Machine Infrastructure Providers Policy
$policyProps = @{
    Name              = $cpVMInfraProvider
    InstanceType      = $instanceTypeObject
    InfraConfigPolicy = $infraConfigPolicyObject
    NodeGroup         = $nodeGroupObject
}

$result = New-IntersightKubernetesVirtualMachineInfrastructureProvider @policyProps
```

**Version used**
 - Intersight PowerShell Module version? 1.0.11.7658
 - Using Intersight SaaS platform

**Expected behavior**
This used to work and stopped working. The expected behavior is, we should be able to link the NodeGroup profile with the Infrastructure provider. 

The API doesn't list this as a "Read-Only" property.

**Comment by savithamr** [comment]
Able to create a Kubernetes Virtual Machine Infrastructure Provider, using the following cmdlets

$instanceTypeObject = New-IntersightKubernetesVirtualMachineInstanceType -name test-instancetype
$infraconfigpolicy = Initialize-IntersightKubernetesVirtualMachineInfraConfigPolicy -name test-infraconfigpolicy
$nodegroupprofile = Get-IntersightKubernetesNodeGroupProfile -name "kubernetes_node_group_profile1"
 
$policyProps = @{
    Name              = "test-kubernetes_virtual_machine_infrastructure_provider"
    InstanceType      = $instanceTypeObject
    InfraConfigPolicy = $infraconfigpolicy
    NodeGroup         = $nodegroupprofile
}

$result = New-IntersightKubernetesVirtualMachineInfrastructureProvider @policyProps

**Comment by sandkum5** [comment]
The provided code does work. Thank you for this. 

I am using the "Initialize-IntersightMoMoRef" for various other objects and that seems to work fine. 

Any reason why the "Initialize-IntersightMoMoRef" fails and the "Get-IntersightKubernetesNodeGroupProfile" works fine? 

Trying to understand when to use "Initialize-IntersightMoMoRef" vs "Get-.. " commands. 

Appreciate all the help.

**Comment by savithamr** [comment]
One can use MoMoRef when the type is "Relationship" to get the reference 
The below cmdlets worked fine:

$instanceTypeObject_ref = Initialize-IntersightMoMoRef -ClassId "MoMoRef" -ObjectType "kubernetesVirtualMachineInstanceType" -Selector "Name eq 'test-instancetype'"  

$infraconfigpolicy1 = Initialize-IntersightKubernetesVirtualMachineInfraConfigPolicy -name test-infraconfigpolicy
$nodegroupprofile_ref = Initialize-IntersightMoMoRef -ClassId "MoMoRef" -ObjectType "kubernetesNodeGroupProfile" -Selector "Name eq 'kubernetes_node_group_profile1'"
 
$policyProps_ref = @{
    Name              = "test-kvm_frastructure_provider"
    InstanceType      = $instanceTypeObject_ref
    InfraConfigPolicy = $infraconfigpolicy1
    NodeGroup         = $nodegroupprofile_ref
}

$result = New-IntersightKubernetesVirtualMachineInfrastructureProvider @policyProps_ref 

-------------------------
Able to reproduce the error when the "NodeGroupProfile" doesn't exists. 

$nodegroupprofile_ref = Initialize-IntersightMoMoRef -ClassId "MoMoRef" -ObjectType "kubernetesNodeGroupProfile" -Selector "Name eq 'kubernetes_node_group_profile1_doesntexists'"
 
$policyProps_ref = @{
    Name              = "test-kvm_frastructure_provider"
    InstanceType      = $instanceTypeObject_ref
    InfraConfigPolicy = $infraconfigpolicy1
    NodeGroup         = $nodegroupprofile_ref
}

$result = New-IntersightKubernetesVirtualMachineInfrastructureProvider @policyProps_ref

New-IntersightKubernetesVirtualMachineInfrastructureProvider: Error calling CreateKubernetesVirtualMachineInfrastructureProvider: {"code":"InvalidRequest","message":"The request body contains the 'NodeGroup' relationship, which is read-only. Do not include read-only relationships in the request body","messageId":"barcelona_request_cannot_modify_read_only_relationships","messageParams":{"1":"NodeGroup"},"traceId":"Tn9fzz4IHH5bpd-djLlqnxFUfC15xgz4Rh6Hn6k_8ubEB9UWrBDgYQ=="}

**Comment by sandkum5** [comment]
Thank you for sharing the details. The response error "The request body contains the 'NodeGroup' relationship, which is read-only. Do not include read-only relationships in the request body" is confusing when an object doesn't exist.

I think this can be updated to reflect the actual error. 

Additionally, not every relationship object seems to require a "MoMoRef" object. 

```
E.g. 
For cmdlet: New-IntersightKubernetesNodeGroupProfile below parameters are all relationship objects. 

-ClusterProfile           <KubernetesClusterProfileRelationship>
-KubernetesVersion  <KubernetesVersionPolicyRelationship>
-IpPools                      <System.Collections.Generic.List`1[IppoolPoolRelationship]>
```

```
# Initialize Objects
$clusterProfileObject = Get-IntersightKubernetesClusterProfile -Moid $moids.cluster_profile_moid
$kubernetesVersionObject = Get-IntersightKubernetesVersionPolicy -Moid $moids.kube_version_moid
$ipPoolsObject = Get-IntersightIppoolPool -Moid $moids.ippool_moid

# Create Kubernetes Node Group Profile
$policyProps = @{
    Name              = $cpName
    NodeType          = $cpNodeType
    Desiredsize       = $cpDesiredSize
    Minsize           = $cpMinSize
    Maxsize           = $cpMaxSize
    ClusterProfile    = $clusterProfileObject
    KubernetesVersion = $kubernetesVersionObject
    IpPools           = $ipPoolsObject
}
$result = New-IntersightKubernetesNodeGroupProfile @policyProps
```

Above returns the following error:

```
New-IntersightKubernetesNodeGroupProfile: Error calling CreateKubernetesNodeGroupProfile: {"code":"InvalidRequest","message":"Cannot execute the request. The JSON document is malformed.","messageId":"barcelona_request_malformed_json","messageParams":{},"traceId":"xbBpGfV1qqmQc1HJPJFRB4iDPfMGhHs50wWTWCHAAPpm6cRPI4_Q5Q==","cause":{"code":"InvalidRequest","message":"Invalid value for the 'class' property. The object reference 'kubernetes.NodeGroupProfile:IpPools' has Class 'ippool.Pool'. It should be 'mo.MoRef'.","messageId":"barcelona_moref_validation_class_not_correct","messageParams":{"1":"kubernetes.NodeGroupProfile","2":"IpPools","3":"ippool.Pool","4":"mo.MoRef"},"traceId":"xbBpGfV1qqmQc1HJPJFRB4iDPfMGhHs50wWTWCHAAPpm6cRPI4_Q5Q=="}}
```

When we change the ipPoolsObject to below, It works fine. 

```
$ipPoolsObject = Get-IntersightIppoolPool -Moid $moids.ippool_moid | Get-IntersightMoMoRef
```

Kindly advise on how to differentiate when to use  "| Get-IntersightMoMoRef" and when not to use it.

**Comment by savithamr** [comment]
As checked, if the input parameter is array of relationships or if any relationship parameter is part of an array, the internal conversion to change it to MoRef is currently not handled.

So here, both ClusterProfile and KubernetesVersion are single relationship. But IpPools is an array of relationships to ippoolPool resources.  So Array needs to use Get-IntersightMoMoRef to convert all elements.

**Comment by Ghufz** [comment]
Conversion of Relationship parameter is already taken care in SDKs side.
user can directly pass the ManagedObject or MoMOref to relationship parameter.
Explicit conversion to MoRef is not required  like below
```
$ipPoolsObject = Get-IntersightIppoolPool -Moid $moids.ippool_moid | Get-IntersightMoMoRef

```

Cmdlet should work without converting to MoRef
```
$policyProps = @{
    Name              = $cpName
    NodeType          = $cpNodeType
    Desiredsize       = $cpDesiredSize
    Minsize           = $cpMinSize
    Maxsize           = $cpMaxSize
    ClusterProfile    = $clusterProfileObject
    KubernetesVersion = $kubernetesVersionObject
    IpPools           = $ipPoolsObject
}
$result = New-IntersightKubernetesNodeGroupProfile @policyProps
```
