### ISSUE TITLE
The Set-IntersightConfiguration @config -SkipCertificateCheck throws error message in on-prem servers.

### ISSUE THREAD

**Issue by savithamr** [CiscoDevNet/intersight-powershell#78]
**Describe the bug**
The Set-IntersightConfiguration @config -SkipCertificateCheck throws an error message in on-prem servers.

**To Reproduce**
Steps to reproduce the behavior

 
    $config = @{ 
             BasePath = "https://xxxx-onprem-xxxxx.cisco.com"
             ApiKeyId = "xxxxx/xxxxx/xxxxx"
             ApiKeyFilePath = "D:/path/secret.txt"
             HttpSigningHeader =  @("(request-target)", "Host", "Date", "Digest")
     }

	Set-IntersightConfiguration @config -SkipCertificateCheck
	Set-IntersightConfiguration: Error performing this operation. Either invalid BasePath (No such host is known) or invalid SSL Certificates. Use 'SkipCertificateCheck = $true' in configuration for invalid SSL certificates and retry the operation.` 

**Version used**
 - Version Used : 1.0.11.7766

**Expected behavior**
Though the connection to the server is successful, should not throw an error message when Set-IntersightConfiguration is done.

**Comment by dsoper2** [comment]
We'll prioritize a fix - as mentioned in the original issue the connection is successful and the error can be ignored in current versions of the module.

**Comment by Ghufz** [comment]
Unable to reproduce the issue with latest published version v 1.0.11.9661
