### ISSUE TITLE
Documentation is not displayed 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/intersight-powershell#8]
When I go to link: 
https://github.com/CiscoDevNet/intersight-powershell/blob/master/docs/IntersightHyperflexApi.md#New-IntersightHyperflexClusterNetworkPolicy

It shows the following message: 
(Sorry about that, but we can’t show files that are this big right now.)

It should show the right documentation like other modules. 
E.g.: https://github.com/CiscoDevNet/intersight-powershell/blob/master/docs/IntersightNetworkconfigApi.md#New-IntersightNetworkconfigPolicy

**Comment by Ghufz** [comment]
Use the latest Intersight moudle from [PSGallery](https://www.powershellgallery.com/packages/Intersight.PowerShell)

Note :- the latest Intersight Powershell module contains breaking changes. 

For more info about parameter and cmdlet use please refer to cmdlet help. 
```powershell
Get-Help New-IntersightNetworkConfigPolicy -full 
```
