### ISSUE TITLE
Documentation example object is too long (looped)

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/intersight-powershell#9]
When I use the example provided in the link: 
https://github.com/CiscoDevNet/intersight-powershell/blob/master/docs/IntersightNetworkconfigApi.md#New-IntersightNetworkconfigPolicy

$NetworkconfigPolicy = (Initialize-networkconfig.Policy-ClassId "ClassId_example" -O ... **object seems to be too long and have the same parameters repeated multiple times which makes it too long.** 

**I see the same issue with other modules as well.** 
Another example: 
https://github.com/CiscoDevNet/intersight-powershell/blob/88fc023349448992e12b9d5624a0b2888da650d7/docs/IntersightNtpApi.md#New-IntersightNtpPolicy

Look at the $NtpPolicy object: 
$NtpPolicy = (Initialize-ntp.Policy-AccountMoid "AccountMoid_example" -ClassId "ClassId_example" ....

**Comment by Ghufz** [comment]
Use the latest Intersight PowerShell module from (PSGallery)[https://www.powershellgallery.com/packages/Intersight.PowerShell]

for cmdlet usability follow the cmdlet help. 

to create ntp policy with new intersight module :- 
```powershell
$org = Get-IntersightOrganizationOrganization -Name default
$ntp = New-IntersightNtpPolicy -Name TestPolicy -NtpServers @("11.11.11.11") -Enabled $true -Organization $org
```
