### ISSUE TITLE
Set-IntersightFabricVlan sending 0 value for existing vlans

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-powershell#90]
**Describe the bug**
Set-IntersightFabricVlan sending 0 value for vlans

**To Reproduce**
Steps to reproduce the behavior

PS C:\temp> $vlan.VlanId
10
PS C:\temp> Set-IntersightFabricVlan -Moid $vlan.Moid -AutoAllowOnUplinks $true -Vlan $vlan.VlanId -Json
{
  "AutoAllowOnUplinks": true,
  "IsNative": false,
  "Name": "Test_10",
  "VlanId": 0,  <-- Should be 10
  "Moid": "6413a45a6f62692d3268ea30"
}
Set-IntersightFabricVlan: Error calling UpdateFabricVlan: {"code":"InvalidRequest","message":"Cannot set the property 'fabric.Vlan.VlanId'. The minimum value of the property is '1'.","messageId":"barcelona_property_constraints_min_integer_validation","messageParams":{"1":"fabric.Vlan","2":"VlanId","3":1},"traceId":"KFLX4RZ4mzXLrcQhRS2IY1O4I6IxkpinuK27wXu7mRAuhjttZFfP8w=="}

With static assignment of -VlanId every number except the actual vlan id works:

PS C:\temp> Set-IntersightFabricVlan -Moid $vlan.Moid -AutoAllowOnUplinks $true -Vlan 10 -Json
{
  "AutoAllowOnUplinks": true,
  "IsNative": false,
  "Name": "Test_10",
  "VlanId": 0,  <-- not sure why its 0
  "Moid": "6413a45a6f62692d3268ea30"
}
Set-IntersightFabricVlan: Error calling UpdateFabricVlan: {"code":"InvalidRequest","message":"Cannot set the property 'fabric.Vlan.VlanId'. The minimum value of the property is '1'.","messageId":"barcelona_property_constraints_min_integer_validation","messageParams":{"1":"fabric.Vlan","2":"VlanId","3":1},"traceId":"5owSmb1l_IfaJr9GUtywU7Gx8GLP2k6sYfyq9clfYrc7BQQM8exCew=="}

PS C:\temp> Set-IntersightFabricVlan -Moid $vlan.Moid -AutoAllowOnUplinks $true -Vlan 11 -Json
{
  "AutoAllowOnUplinks": true,
  "IsNative": false,
  "Name": "Test_10",
  "VlanId": 11,  <--- changes to what we defined but we need it to be 10...
  "Moid": "6413a45a6f62692d3268ea30"
}
Set-IntersightFabricVlan: Error calling UpdateFabricVlan: {"code":"InternalServerError","message":"Cannot change the VLAN ID! Cannot change the VLAN ID! Old VLAN ID is: 10.","messageId":"gobi_fabric_modify_vlan_id","messageParams":{"1":"Cannot change the VLAN ID! Old VLAN ID is: 10"},"traceId":"ux45UngAUxm-f99JzMBwGo4X65Ok6M2Qbxr6OHkW8w1NMpLYFaW5Dg=="}

**Version used**
-Module 1.0.11.7766

**Expected behavior**
Should be able to specify the vlanid of the existing vlan

**Screenshots**

**Additional context**

**Comment by Ghufz** [comment]
Please give a try with latest module which is https://www.powershellgallery.com/packages/Intersight.PowerShell/1.0.11.11765

**Comment by Ghufz** [comment]
tested this it is working as expected. whatever value is provided it is able to set.
