### ISSUE TITLE
Set-IntersightHyperflexSoftwareVersionPolicy -UpgradeTypes input type doesn't match help page description

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-powershell#92]
**Describe the bug**
Set-IntersightHyperflexSoftwareVersionPolicy -UpgradeTypes input type doesn't match help page description

From Get-Help:
 -UpgradeTypes <System.Collections.Generic.List`1[string]>
        Required?                    false
        Position?                    named
        Default value                None
        Accept pipeline input?       True (ByPropertyName)
        Accept wildcard characters?  false

Error Output:
Set-IntersightHyperflexSoftwareVersionPolicy: Unable to cast object of type 'System.Collections.Generic.List`1[Intersight.Model.HyperflexSoftwareVersionPolicy+UpgradeTypesEnum]' to type 'System.Collections.Generic.IEnumerable`1[System.Object]'.

Tried lists, arrays, individual strings, references to IntersightHyperflexServerFirmwareVersionInfo objects etc.. 

**To Reproduce**
$hxClusterProfileName = "dcloud-hx-edge-cluster-1"
$hxdpVersion = "5.0(2a)-41731"
$hypervisorVersion = "HX-ESXi-7.0U3-20328353-Cisco-Custom-7.3.0.10"
$serverFirmwareVersion = "4.1(3f)"
$serverPlatform = "M5"
$upgradeType = "HXDP","Hypervisor","ServerFirmware"

$hxClusterProfile = Get-IntersightHyperflexClusterProfile -Top 1 -Filter ("Name eq '" + $hxClusterProfileName + "'")

$upgradeType = Initialize-IntersightHyperflexSoftwareVersionPolicy -UpgradeTypes $upgradeType
$serverFirmwareVersionInfo = Initialize-IntersightHyperflexServerFirmwareVersionInfo -ServerPlatform $serverPlatform -Version $serverFirmwareVersion

$setSoftwareVersionResults = Set-IntersightHyperflexSoftwareVersionPolicy -Moid $hxClusterProfile.Results.SoftwareVersion.ActualInstance.Moid -HypervisorVersion $hypervisorVersion -ServerFirmwareVersions $serverFirmwareVersionInfo -HxdpVersion $hxdpVersion -UpgradeTypes $upgradeType.UpgradeTypes

**Version used**
Intersight SaaS
Powershell Module 1.0.11.7766

**Expected behavior**
Should be able to use UpgradeTypes parameter

**Screenshots**

**Additional context**

**Comment by briamorr** [comment]
User error, was able to get it working with the following:
$upgradeType = New-Object System.Collections.Generic.List[string]
$upgradeType.add("HXDP")
$upgradeType.add("Hypervisor")
$upgradeType.add("ServerFirmware")

**Comment by Ghufz** [comment]
The above fix has been provided, it will available in the next release of Intersight.Powershell module.(any release after this version [1.0.11.12738](https://www.powershellgallery.com/packages/Intersight.PowerShell/1.0.11.12738))
