### ISSUE TITLE
Question - How to get Mac-Address and WWPN / WWNN from ServerProfiles which are not assigned to a server

### ISSUE THREAD

**Issue by rfiodv** [CiscoDevNet/intersight-powershell#97]
**Question**
How to get Mac-Address and WWPN / WWNN from ServerProfiles which are not assigned to a server  
$ETHInventoryList = Get-IntersightManagedObject -ObjectType vnic.EthIfInventory | ConvertFrom-Json -> only return the needed information if the ServerProfile is assigned to a server  
Same behavior with ->  $FCInventorylist = Get-IntersightManagedObject -ObjectType vnic.FcIfInventory | ConvertFrom-Json   

**To Reproduce**
$ETHInventoryList = Get-IntersightManagedObject -ObjectType vnic.EthIfInventory | ConvertFrom-Json
$FCInventorylist = Get-IntersightManagedObject -ObjectType vnic.FcIfInventory | ConvertFrom-Json

**Version used**
 - Intersight PowerShell Module version? - 1.0.11.9783
 - Intersight Appliance Version (if using an Intersight Appliance as target) - 1.0.9-558

**Expected behavior**
Returns MAC and WWPN / WWNN, no matter ServerProfile is assigned to a server or not.
Intersight GUI shows also MAC and WWPN / WWNN, when no server is assigned

**Comment by briamorr** [comment]
Do you have more than 100 vnics being returned?  By default if no top parameter is specified Intersight will only return 100 objects which might be why some data is missing if you have >100.  

Have you tried a more specific query like the following to see if the mac's (or wwpns with Get-IntersightVnicFcIf) show up on an unassigned profile:

```
$ServerProfile = Get-IntersightServerProfile -Name myunassigned-profile
$filter = "Profile.Moid eq '" + $ServerProfile.Moid + "'"
$vNICs = Get-IntersightVnicEthIf -Filter $filter
$vNICs.Results | Select-Object Name,MacAddress

Name   MacAddress
----   ----------
vnic-A 00:25:B5:D3:33:7E
vnic-B 00:25:B5:D3:33:7F
```

**Comment by rfiodv** [comment]
In fact, this way, with the filter method, I have not even tried.
I have tried to get the identifier out somehow via Get-IntersightVnicEthIF or via the ServerProfile.
Therefore also the attempt with 
``` 
 $ETHInventoryList = Get-IntersightManagedObject -ObjectType vnic.EthIfInventory | ConvertFrom-Json
``` 
Is there any other way besides the filter method ?
I find it a bit difficult to derive the filter method.

**Comment by briamorr** [comment]
You can avoid the $filter and use $top/$skip instead to retrieve all the objects if you have more than 1000.

What is the end goal you are trying to accomplish a list of profiles and their WWPNs & MACs?

If so this might be another option:
```
$ServerProfiles = Get-IntersightServerProfile -Top 1000

foreach($ServerProfile in $ServerProfiles.Results)
{
	$MORef = Get-IntersightMoMoRef -ManagedObject $ServerProfile
	$vHBAs = Get-IntersightVnicFcIf -Profile $MORef | Select Name,Wwpn
	$vNICs = Get-IntersightVnicEthIf -Profile $MORef | Select Name,MacAddress
	$vNICs | ForEach-Object { "$($ServerProfile.Name) $($_.Name) $($_.MacAddress)" }
	$vHBAs | ForEach-Object { "$($ServerProfile.Name) $($_.Name) $($_.Wwpn)" }

}

```

Output Example (I only have 1 vHBA defined and unassigned/not assigned profiles that show up): 
```
IMM-FI-LOAN-Chassis1-Blade1 vnicB 00:25:B5:D3:33:8F
IMM-FI-LOAN-Chassis1-Blade1 vnicA 00:25:B5:D3:33:8E
IMM-FI-LOAN-Chassis1-Blade1 vhbaA 20:00:00:25:B5:BB:00:10
IMM-FI-LOAN-Chassis1-Blade3 vnicB 00:25:B5:D3:33:35
IMM-FI-LOAN-Chassis1-Blade3 vnicA 00:25:B5:D3:33:34
IMM-FI-LOAN-Chassis1-Blade4 vnicB 00:25:B5:D3:33:8A
IMM-FI-LOAN-Chassis1-Blade4 vnicA 00:25:B5:D3:33:8B
IMM-FI-LOAN-Chassis1-Blade2 vnicB 00:25:B5:D3:33:39
IMM-FI-LOAN-Chassis1-Blade2 vnicA 00:25:B5:D3:33:3A
```

**Comment by ThatWindowsGuy** [comment]
What method are you using to get the WWNN from the Server Profile?  Getting the WWPN is easy enough with Get-IntersightVnicFcIf, but it doesn't expose the WWNN.

**Comment by rfiodv** [comment]
Work for me.

Thank you !
